# Generated by Django 2.2.4 on 2020-02-05 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_profile',
            fields=[
                ('company_useremail', models.EmailField(max_length=225, primary_key=True, serialize=False)),
                ('company_userpassword', models.CharField(max_length=1000)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=255)),
                ('postal_code', models.IntegerField(null=True)),
                ('state_province', models.CharField(max_length=255)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('mobile_number', models.CharField(default='', max_length=15)),
                ('fax', models.CharField(max_length=50)),
                ('website_url', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('profile_updated', models.BooleanField(default=False)),
                ('password_updated', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField()),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Firstapp.roles')),
            ],
        ),
    ]
