# Generated by Django 2.2.4 on 2020-02-06 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0002_company_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('user_firstname', models.CharField(max_length=255)),
                ('user_lastname', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=255)),
                ('user_password', models.CharField(max_length=1000)),
                ('username', models.CharField(default='', max_length=255)),
                ('user_company_email', models.CharField(default='', max_length=255)),
                ('user_company', models.CharField(default='', max_length=255)),
                ('user_phone', models.CharField(default='', max_length=15)),
                ('user_employee_id', models.CharField(default='', max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('employee_read', models.BooleanField(default=False, null=True)),
                ('employee_create', models.BooleanField(default=False, null=True)),
                ('employee_edit', models.BooleanField(default=False, null=True)),
                ('employee_delete', models.BooleanField(default=False, null=True)),
                ('leaves_read', models.BooleanField(default=False, null=True)),
                ('leaves_create', models.BooleanField(default=False, null=True)),
                ('leaves_edit', models.BooleanField(default=False, null=True)),
                ('leaves_delete', models.BooleanField(default=False, null=True)),
                ('holidays_read', models.BooleanField(default=False, null=True)),
                ('holidays_create', models.BooleanField(default=False, null=True)),
                ('holidays_edit', models.BooleanField(default=False, null=True)),
                ('holidays_delete', models.BooleanField(default=False, null=True)),
                ('event_read', models.BooleanField(default=False, null=True)),
                ('event_create', models.BooleanField(default=False, null=True)),
                ('event_edit', models.BooleanField(default=False, null=True)),
                ('event_delete', models.BooleanField(default=False, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_date', models.CharField(default='', max_length=255)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Firstapp.roles')),
            ],
        ),
    ]
