# Generated by Django 2.2.4 on 2020-02-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0003_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
                ('added_by', models.CharField(default='', max_length=255)),
                ('edited_by', models.CharField(default='', max_length=255)),
                ('deleted_by', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
