# Generated by Django 2.2.4 on 2020-02-06 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0005_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_profile',
            fields=[
                ('employee_firstname', models.CharField(max_length=255)),
                ('employee_lastname', models.CharField(max_length=255)),
                ('employee_username', models.CharField(default='', max_length=255)),
                ('employee_official_email', models.EmailField(default='', max_length=255)),
                ('employee_personal_email', models.EmailField(default='', max_length=255)),
                ('employee_password', models.CharField(max_length=1000)),
                ('employee_company', models.CharField(max_length=255)),
                ('employee_hr_name', models.CharField(default='', max_length=255)),
                ('employee_company_email', models.CharField(default='', max_length=255)),
                ('employee_hr_email', models.CharField(default='', max_length=255)),
                ('employee_phone', models.CharField(default='', max_length=15)),
                ('employee_employee_id', models.CharField(default='', max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('profile_edit', models.BooleanField(default=False)),
                ('added_by', models.CharField(max_length=255)),
                ('edited_by', models.CharField(max_length=255)),
                ('deleted_by', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_terminated', models.BooleanField(default=False)),
                ('terminated_by', models.CharField(default='', max_length=255)),
                ('promoted_by', models.CharField(default='', max_length=255)),
                ('created_date', models.CharField(default='', max_length=255)),
                ('terminated_date', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(default='', max_length=50, null=True)),
                ('birthday', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=500)),
                ('martial_status', models.CharField(default='', max_length=255)),
                ('masters_college_name', models.CharField(default='', max_length=500)),
                ('masters_college_course_name', models.CharField(default='', max_length=500)),
                ('masters_college_details', models.CharField(default='', max_length=500)),
                ('masters_start_year', models.CharField(default='', max_length=4)),
                ('masters_complete_year', models.CharField(default='', max_length=4)),
                ('graduation_college_name', models.CharField(default='', max_length=500)),
                ('graduation_college_course_name', models.CharField(default='', max_length=500)),
                ('graduation_college_details', models.CharField(default='', max_length=500)),
                ('graduation_start_year', models.CharField(default='', max_length=4)),
                ('graduation_complete_year', models.CharField(default='', max_length=4)),
                ('sec_schl_name', models.CharField(default='', max_length=500)),
                ('sec_schl_board', models.CharField(default='', max_length=255)),
                ('sec_schl_details', models.CharField(default='', max_length=500)),
                ('sec_schl_complete_year', models.CharField(default='', max_length=4)),
                ('matric_schl_name', models.CharField(default='', max_length=500)),
                ('matric_schl_board', models.CharField(default='', max_length=255)),
                ('matric_schl_details', models.CharField(default='', max_length=500)),
                ('matric_schl_complete_year', models.CharField(default='', max_length=4)),
                ('permission_to_edit', models.BooleanField(default=False)),
                ('updated_once', models.BooleanField(default=False)),
                ('request_status', models.IntegerField(default=0)),
                ('edit_request_hr_email', models.CharField(default='', max_length=255)),
                ('edit_request_emp_email', models.CharField(default='', max_length=255)),
                ('edit_request_by_emp', models.BooleanField(default=False)),
                ('edit_request_by_hr', models.BooleanField(default=False)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Firstapp.department')),
                ('designation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Firstapp.designation')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Firstapp.roles')),
            ],
        ),
    ]
